[package]
name = "wsol"
version = "0.1.0"
description = "Created with Anchor"
edition = "2021"

[lib]
crate-type = ["cdylib", "lib"]
name = "wsol"

[features]
default = []
cpi = ["no-entrypoint"]
no-entrypoint = []
no-idl = []
no-log-ix-name = []
idl-build = ["anchor-lang/idl-build", "anchor-spl/idl-build"]
anchor-debug = []


[dependencies]
anchor-lang = { version = "0.30.1", default-features = true, features = [
  "init-if-needed",
  "event-cpi",
] }
anchor-spl = { version = "0.30.1", default-features = true }

